Repository FIS2425/api-gateway, pull requests merged in 2024-11, with the labels that each got.

#10 Feature/8 logger
  Cargo.lock
  Cargo.toml
  config.yaml
  src/config/logger.rs
  src/config/mod.rs
  src/config/parser.rs
  src/main.rs
Labels: 😎 size/m

#14 feat: update renovate config
  .devcontainer/devcontainer.json
  .github/CODEOWNERS
  .github/renovate.json
Labels: 🏠 Github Configuration, 🚀 CI/CD

#20 fix: fixed docker workflow
  .github/workflows/docker-deploy.yml
  Dockerfile
Labels: 🐳 Dockerize, 🚀 CI/CD, 🐳 Build, size/xs

#18 fix: added standard header to preserve original sender ip
  Cargo.lock
  Cargo.toml
  src/main.rs
Labels: size/s

#23 feat: passed request_id as a header to microservices
  src/main.rs
Labels: size/xs

#19 feature: added open api merger
  Cargo.lock
  Cargo.toml
  config.yaml.example
  docs/.last_updated
  openapi.html
  openapi.yaml
  src/config/mod.rs
  src/config/openapi.rs
  src/config/parser.rs
  src/main.rs
Labels: 😎 size/m

#28 feat: enhance workflows
  .github/workflows/rust.yml
  .github/workflows/sync-openapi.yml
  openapi.html
Labels: 🚀 CI/CD, size/s

#38 feat(deploy): added kubernetes deploy
  kubernetes/api-gateway-data-persistentvolumeclaim.yaml
  kubernetes/api-gateway-deployment.yaml
  kubernetes/api-gateway-service.yaml
Labels: size/s
