Repository FIS2425/api-gateway, pull requests merged in 2024-12, with the labels that each got.

#39 chore: updated config.yaml.example
  config.yaml.example
Labels: size/s

#43 feat: added staff routes to config
  config.yaml.prod
Labels: 🐳 Dockerize, size/xs

#45 Feature/ws ap to config
  config.yaml.prod
Labels: size/s

#44 ci: apiclient dispatch
  .github/workflows/openapi.yml
Labels: 🚀 CI/CD, size/s
