Repository FIS2425/api-gateway, pull requests merged in 2025-01, with the labels that each got.

#49 chore: add payments service to configuration
  config.yaml.example
  config.yaml.prod
Labels: size/xs

#46 fix: output path on merger
  .github/workflows/openapi.yml
  README.md
Labels: 📝 Documentation, 🚀 CI/CD

#50 fix(config): added patient and payment endpoints
  config.yaml.example
  config.yaml.prod
Labels: size/s

#51 config: add workflow to deploy to AKS
  .github/workflows/deploy-aks.yaml
Labels: 🚀 CI/CD, size/s
